### ISSUE TITLE
equals method in ReflectionEnum should be type-hinted

### ISSUE THREAD

**Issue by garak** [damianopetrungaro/clean-architecture#14]
I'm implementing ReflectionEnum, so I added the method:
``` php
<?php

namespace Foo;

use Damianopetrungaro\CleanArchitecture\Common\Enum\ReflectionEnum;

class Bar extends ReflectionEnum
{
    private const BAZ = 1;

    public  function equals($enum): bool
    {
        return $this->value === $enum->getValue();
    }
}
```
Problem is I cannot really use `$enum->getValue()`, unless `$enum` is type-hinted against ReflectionEnum

**Comment by damianopetrungaro** [comment]
Hey @garak  thank you for the issue!
Yeah, seem that on abstract methods isn't possible to add type hint on the child class.

I guess we should just add the `Enum` type hint on it. `public  function equals(Enum $enum): bool`
If you have any other suggestion feel free to help, PR is welcome if you're free!

**Comment by garak** [comment]
What about this?

```php
    public  function equals(ReflectionEnum $enum): bool
    {
        return $this->value === $enum->getValue();
    }
```

**Comment by damianopetrungaro** [comment]
`ReflectionEnum` is an implementation of the interface `Enum`.

If we are going to type hint it I prefer using the interface, so custom implementation are will be supported 😄

**Comment by damianopetrungaro** [comment]
@garak  are you free to work on it?
Otherwise, I'll schedule some time next week 😄

**Comment by garak** [comment]
See #15

**Comment by damianopetrungaro** [comment]
Ty @garak for improving this package!
