### ISSUE TITLE
I'm a bit confused and don't understand your logic with Enum

### ISSUE THREAD

**Issue by bigfoot90** [damianopetrungaro/clean-architecture#5]
Ralated with https://github.com/damianopetrungaro/clean-architecture/pull/3
Excuse me if I'm insisting on this argument, but I'm a bit confused and don't understand your logic with **Enum**.

By your current implementation, you're forcing the developers to set the values same as the constant name [like in your test](https://github.com/bigfoot90/clean-architecture/blob/2e031c891dcfda0c5d28f394e3a8697c62bf0c56/tests/Unit/Common/Enum/Fixtures/MyEnum.php).

Now, please see this example implemented with python lnaguage: https://en.wikipedia.org/wiki/Enumerated_type#Dynamically_typed_languages
```python
from enum import Enum
class Shape(Enum):
    circle = 1
    triangle = 2
    square = 3
    hexagon = 4

def has_vertices(shape):
    return shape != Shape.circle
```
**Advantages**
* Comparation between integers is much much faster than comparing two strings
* Integer require less memory to be stored in database and indices are faster

**Currently**
* I don't understand why the constant value must be equal to its name.
* With factories `Shape::CIRCLE()` you cannot use the *search by usage*, and this make the software not maintenable in long time.
* In addition you cannot use *refactor* function from your IDE.

If I'm missing something, please tell me.

**Comment by damianopetrungaro** [comment]
Don't worry the issues are here for this reason 😄 

At the moment in the Enum is possible use different name and value, [see here](https://github.com/damianopetrungaro/clean-architecture/blob/master/tests/Unit/Common/Enum/Fixtures/MyEnum.php), and is possible to use constructor as well!

If you're still missing something comment or close the issue 😄 
Thank you!

**Comment by bigfoot90** [comment]
You're right, I'm trying your code now http://sandbox.onlinephpfunctions.com/code/e73671c763045788a9b613bfdd88cfadc76dc15c
and this is working fine.

I was misreading your code. sorry.
Closing this.
